### ISSUE TITLE
Can't update or install the latest version

### ISSUE THREAD

**Issue by Warren-Vasavah** [williamstudios/zklib-32LE#1]
Dear, @williamstudios 

Hi, I'm Warren from the Philippines. I've been using your package and it is running smoothly, I've been trying to install or update the latest version zklib-32ble@2.0.2 and it is getting an error because of the dependency non-existence. Here is the screenshot of the error I'm encountering.

Google Drive Link:
https://drive.google.com/file/d/157Vve5zJtSTg91DYm9iURrx4YFhqqWux/view?usp=sharing

I hope this will help. Have a great day. Thank you

**Comment by williamstudios** [comment]
I just updated version 2.0.4 where that dependency is removed.
