### ISSUE TITLE
Promise Rejected Error

### ISSUE THREAD

**Issue by asadk6103** [williamstudios/zklib-32LE#2]
I am using this library to connect with my zkteco device. It shows me an error saying
```
ok tcp
{ data: null }
Promise Rejected
```

Any idea?

**Comment by williamstudios** [comment]
Hello, when you receive oktcp it means that the connection to the device is successful

when you use a function to obtain data for example
const users = await zkInstance.getUsers() 
and you receive the Promise Rejected error it means that there is no data inside the device

**Comment by asadk6103** [comment]
I am fetching data from the same device using puck and it gets record from machine. That comment does not answer my question.

**Comment by williamstudios** [comment]
Please can you post your example code?
The library only works with assistive devices, it does not work with security door devices.
